#!/usr/bin/env python3
"""Warn about commit subjects breaking the `type: description` format.

A portable, path-generic checker: copy this file into any repo and run
it in CI on `pull_request` events, over a `--base`/`--head` commit range.
Not a drop-in `commit-msg` hook: that hook receives a message-file path,
not two refs. Strips a trailing GitHub squash-merge suffix (` (#123)`)
before checking length, since that suffix is not user-authored. Skips merge
commits for the same reason: `git merge` writes "Merge branch 'x' into y",
which no author chose and which no `type: description` subject can express.
Cannot verify imperative mood, only shape. Always exits 0, even when it finds
violations; this check is advisory, not blocking.
"""
import argparse
import os
import re
import subprocess
import sys

try:
    from scripts.trusted_git import run_git
except ModuleNotFoundError:
    from trusted_git import run_git

SUBJECT_PATTERN = re.compile(r"^(feat|fix|chore|docs|test): \S.*$")
SQUASH_SUFFIX = re.compile(r" \(#\d+\)$")
MAX_LENGTH = 50


def _strip_squash_suffix(subject: str) -> str:
    """Remove a trailing GitHub squash-merge ` (#123)` suffix, if present."""
    return SQUASH_SUFFIX.sub("", subject)


def find_violations(subjects: list[tuple[str, str]]) -> list[str]:
    """Return one message per commit subject violating the format rule.

    `subjects` is a list of (sha, subject) pairs.
    """
    violations = []
    for sha, raw_subject in subjects:
        short_sha = sha[:12]
        prefix = f"{short_sha}: " if short_sha else ""
        subject = _strip_squash_suffix(raw_subject)
        if not SUBJECT_PATTERN.match(subject):
            violations.append(
                f"warning: {prefix}subject '{raw_subject}' must start with "
                "'type: description' (feat, fix, chore, docs, test)"
            )
            continue
        if len(subject) > MAX_LENGTH:
            violations.append(
                f"warning: {prefix}subject '{raw_subject}' exceeds {MAX_LENGTH} "
                f"characters ({len(subject)})"
            )
        if subject.endswith("."):
            violations.append(f"warning: {prefix}subject '{raw_subject}' ends with a period")
    return violations


def load_commits(base: str, head: str, repo=None) -> list[tuple[str, str]]:
    """Collect (sha, subject) pairs for the base..head range via git log.

    Merge commits are excluded: their subject is generated by git rather
    than written by a person, so holding it to an authoring convention
    fails every ordinary branch update.
    """
    repository = repo or os.getcwd()
    result = run_git(
        repository,
        [
            "log",
            "--no-merges",
            "--no-ext-diff",
            "--format=%H%x00%s",
            "--end-of-options",
            f"{base}..{head}",
        ],
        check=True,
        runner=subprocess.run,
    )
    commits = []
    for line in result.stdout.splitlines():
        if not line:
            continue
        fields = line.split("\x00")
        if len(fields) != 2 or not re.fullmatch(r"[0-9a-fA-F]{40,64}", fields[0]):
            raise ValueError("git log returned malformed commit metadata")
        sha, subject = fields
        commits.append((sha, subject))
    return commits


def check(base: str, head: str, repo=None) -> int:
    """Warn on violations in the base..head commit range. Always returns 0."""
    violations = find_violations(load_commits(base, head, repo))
    if violations:
        for message in violations:
            print(message)
    else:
        print("no commit-message violations found")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True, help="base ref (exclusive)")
    parser.add_argument("--head", required=True, help="head ref (inclusive)")
    parser.add_argument("--repo", default=os.getcwd(), help="repository to inspect (default: cwd)")
    args = parser.parse_args()
    try:
        return check(args.base, args.head, args.repo)
    except (OSError, subprocess.CalledProcessError, UnicodeError, ValueError) as error:
        print(f"error: git log failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
